"""Static defaults for the independent Futures engine."""

from __future__ import annotations

import os
from pathlib import Path

from platform_v2.shared.backend.runtime_store import system_runtime_root


FUTURES_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_ROOT = system_runtime_root("futures")
STATE_DIR = RUNTIME_ROOT / "state"
EXECUTION_PROFILE_PATH = STATE_DIR / "execution_profile.json"
DOTENV_PATH = FUTURES_ROOT.parents[1] / ".env"


def _load_dotenv(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_dotenv(DOTENV_PATH)

DEFAULT_SYMBOL = "BTCUSDT"
DEFAULT_TIMEFRAME = "15m"
# 1m is execution monitoring only; strategy indicators remain 5m/15m/4h.
DEFAULT_FETCH_TIMEFRAMES = ("1m", "5m", "15m", "4h")
DEFAULT_CANDLE_TIMEFRAMES = ("5m", "15m", "4h")
DEFAULT_CANDLE_LIMIT = 200
EXIT_MONITORING_TIMEFRAME = "1m"
DEFAULT_MODE = "simulation"  # simulation | live
SPOT_ONLY_MODE = True
DEFAULT_LEVERAGE = 5
MIN_LEVERAGE = 1
MAX_LEVERAGE = 50
DEFAULT_MARGIN_MODE = "isolated"  # isolated | cross
DEFAULT_ORDER_SIZE_USDT = 100.0
DEFAULT_STARTING_BALANCE = 3000.0
MAKER_FEE_PCT = 0.0002
TAKER_FEE_PCT = 0.0005
ENTRY_FEE_PCT = TAKER_FEE_PCT
EXIT_FEE_PCT = MAKER_FEE_PCT
# Futures ledgers are cumulative; no artificial day limit is applied.
DEFAULT_LOOKBACK_DAYS: int | None = None

# Signal thresholds / regime gates
BUY_THRESHOLD = 8.5
STRATEGY_VERSION = "futures-short-zone-required-long-profit-lock-1m-v5"
LONG_PROFIT_LOCK_ENABLED = True
LONG_PROFIT_LOCK_ACTIVATION_FRACTION = 0.70
LONG_PROFIT_LOCK_FRACTION = 0.25
# Persist the real histogram history, but do not reward its sequence in live
# scoring until the repaired behavior passes portfolio replay and shadow mode.
MACD_HISTOGRAM_SIGNAL_ENABLED = False
SELL_THRESHOLD = 10.0
REGIME_ADX_MIN = 20.0
ATR_SPIKE_MULTIPLIER = 1.10
SWING_LOOKBACK = 20
SWING_ABOVE_PCT = 0.005
BOUNCE_LOOKBACK = 3
RESISTANCE_LOOKBACK = 30
LIQUIDITY_LOOKBACK = 30
LIQUIDITY_VOLUME_MULTIPLIER = 1.15
LIQUIDITY_TOLERANCE_ATR_MULTIPLIER = 0.8

# Orderbook filters
ORDERBOOK_BUY_SELL_RATIO_MIN = 1.15
ORDERBOOK_SELL_BUY_RATIO_MIN = 1.15
ORDERBOOK_BULL_DOMINANCE_MIN = 0.25
ORDERBOOK_BEAR_DOMINANCE_MAX = -0.25
ORDERBOOK_BULL_IMBALANCE_MIN = 0.10
ORDERBOOK_BEAR_IMBALANCE_MAX = -0.10
ORDERBOOK_DIRECTIONAL_RATIO_NEUTRAL_MIN = 1.0
ORDERBOOK_DIRECTIONAL_RATIO_HEALTHY_MIN = 1.15
ORDERBOOK_DIRECTIONAL_RATIO_STRONG_MIN = 1.5
ORDERBOOK_DIRECTIONAL_RATIO_EXTREME_MIN = 2.0
ORDERBOOK_DIRECTIONAL_RATIO_BLOWOFF_MIN = 3.0
ORDERBOOK_DIRECTIONAL_DOMINANCE_HEALTHY_MIN = 0.10
ORDERBOOK_DIRECTIONAL_DOMINANCE_STRONG_MIN = 0.25
ORDERBOOK_DIRECTIONAL_DOMINANCE_EXTREME_MIN = 0.50
ORDERBOOK_DIRECTIONAL_IMBALANCE_CONFIRM_MIN = 0.05
ORDERBOOK_DIRECTIONAL_IMBALANCE_EXTREME_MIN = 0.50

# SHORT momentum quality filters
SHORT_MOMENTUM_DIRECTIONAL_RSI_EARLY_MIN = 50.0
SHORT_MOMENTUM_DIRECTIONAL_RSI_HEALTHY_MIN = 52.0
SHORT_MOMENTUM_DIRECTIONAL_RSI_LATE_MIN = 58.0
SHORT_MOMENTUM_DIRECTIONAL_RSI_EXHAUSTED_MIN = 65.0
SHORT_MOMENTUM_MACD_SPREAD_EARLY_ATR_MIN = -0.20
SHORT_MOMENTUM_MACD_SPREAD_CONFIRM_ATR_MIN = 0.0
SHORT_MOMENTUM_MACD_SPREAD_LATE_ATR_MIN = 0.20
SHORT_MOMENTUM_MACD_SPREAD_EXTREME_ATR_MIN = 0.50

# Structure entry-location quality filters
STRUCTURE_LONG_LOW_DISTANCE_EARLY_ATR_MIN = 1.0
STRUCTURE_LONG_LOW_DISTANCE_HEALTHY_ATR_MIN = 1.5
STRUCTURE_LONG_LOW_DISTANCE_MID_ATR_MIN = 2.5
STRUCTURE_LONG_LOW_DISTANCE_EXTENSION_ATR_MIN = 4.0
STRUCTURE_LONG_LOW_DISTANCE_BLOWOFF_ATR_MIN = 6.0
STRUCTURE_LONG_SWING_HIGH_ROOM_MIN_ATR = 1.0
STRUCTURE_LONG_SWING_HIGH_ROOM_EXTENDED_ATR = 1.5
STRUCTURE_SHORT_HIGH_DISTANCE_EARLY_ATR_MIN = 1.0
STRUCTURE_SHORT_HIGH_DISTANCE_HEALTHY_ATR_MIN = 1.5
STRUCTURE_SHORT_HIGH_DISTANCE_LATE_ATR_MIN = 2.5
STRUCTURE_SHORT_HIGH_DISTANCE_EXHAUSTED_ATR_MIN = 4.0
STRUCTURE_SHORT_SWING_LOW_ROOM_DANGER_ATR = 0.5
STRUCTURE_SHORT_SWING_LOW_ROOM_HEALTHY_ATR = 1.5
STRUCTURE_SHORT_SWING_LOW_ROOM_LATE_ATR = 2.5
STRUCTURE_SHORT_SWING_LOW_ROOM_EXTENDED_ATR = 4.0

# Weighted scoring
MTF_WEIGHT = 1.0
REGIME_WEIGHT = 0.8
TREND_WEIGHT = 1.3
MOMENTUM_WEIGHT = 1.0
ORDERBOOK_WEIGHT = 0.9
STRUCTURE_WEIGHT = 0.9

SIGNAL_COMPONENT_WEIGHTS = {
    "mtf": MTF_WEIGHT,
    "regime": REGIME_WEIGHT,
    "trend": TREND_WEIGHT,
    "momentum": MOMENTUM_WEIGHT,
    "orderbook": ORDERBOOK_WEIGHT,
    "structure": STRUCTURE_WEIGHT,
}

# Raw gate minimums
MTF_RAW_GATE_MIN = 2.5
MTF_5M_TIMING_SCORE_MIN = 1.1
MTF_PRIMARY_SETUP_SCORE_MIN = 1.0
MTF_HIGHER_CONTEXT_SCORE_MIN = 0.8
REGIME_RAW_GATE_MIN = 1.0
TREND_RAW_MIN = 2.0
MOMENTUM_RAW_GATE_MIN = 2.0
SHORT_MOMENTUM_RAW_GATE_MIN = 1.5
ORDERBOOK_RAW_GATE_MIN = 1.5
STRUCTURE_RAW_GATE_MIN = 1.5
LONG_STRUCTURE_RAW_GATE_MIN = 1.2
SHORT_STRUCTURE_RAW_GATE_MIN = 1.4

# Fallback setup parameters used when theoretical setup is unavailable/invalid.
FALLBACK_TP_PCT = 0.012
FALLBACK_SL_PCT = 0.006

# Entry permission/risk defaults (futures-specific)
MIN_REQUIRED_BALANCE = 100.0
MAX_OPEN_EXPOSURE = 900.0
MAX_OPEN_POSITIONS = 9
MAX_OPEN_POSITIONS_PER_DIRECTION = 9
DEFAULT_PROXIMITY_PCT = 0.5
DEFAULT_COOLDOWN_SECONDS = 2 * 60 * 60
# September 9 stateful replay: the outside-zone exception increased SHORT
# losses. Preserve the zone permission instead of overriding it on score.
SHORT_CONTINUATION_OVERRIDE_ENABLED = False
ENTRY_QUALITY_BLOCKED_TIMINGS = ("EXHAUSTED_MOVE", "LATE_EXTENSION")
FLIP_CONFIRMATION_REQUIRED_SIDES: tuple[str, ...] = ("SHORT",)
FLIP_CONFIRMATION_TIMEFRAME_MS = 15 * 60 * 1000
SHORT_STOP_CAP_ENABLED = True
SHORT_STOP_CAP_BAND_MIN_ATR = 2.5
SHORT_STOP_CAP_BAND_MAX_ATR = 3.5
SHORT_STOP_CAP_ATR = 2.5
LONG_ENTRY_BLOCKED_LOCATIONS = ("EXTENDED", "EXTENDED_INTO_RESISTANCE", "OVERHEATED_EXTENSION")
MAINTENANCE_MARGIN_PCT = 0.005
LIQUIDATION_BUFFER_PCT = 0.01

# Telegram bot alerts
TELEGRAM_BOT_ENABLED = os.getenv("TELEGRAM_BOT_ENABLED", "false").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
