"""Shared persistence adapters and runtime database gates."""

from .database_paths import (
    ACTIVE_DATABASE_PATHS,
    CONTENT_DATABASE_PATH,
    LEGACY_RUNTIME_DATABASE_PATH,
    MARKET_DATA_DATABASE_PATH,
    TRADING_DATABASE_PATH,
    sqlite_sidecar_paths,
)
from .sqlite_content_store import (
    content_database_status,
    initialize_content_database,
    list_news_batches,
    read_news_batch,
    replace_news_batch,
    replace_news_batch_safely,
)
from .sqlite_market_data_store import (
    initialize_market_database,
    list_market_series,
    market_database_status,
    market_series_parity,
    read_market_series,
    read_market_series_safely,
    replace_market_series,
    replace_market_series_safely,
)
from .sqlite_runtime_state import delete_runtime_state, read_runtime_state, write_runtime_state

from .sqlite_runtime_store import (
    DEFAULT_DATABASE_PATH,
    clear_system_documents,
    database_status,
    export_document_to_json,
    import_json_document,
    initialize_database,
    list_documents,
    mirror_daily_json_path_safely,
    mirror_document_safely,
    parity_for_document,
    read_daily_json_dict,
    read_daily_json_list,
    read_document,
    read_latest_document,
    read_family_rows,
    remove_family_documents_except,
)

__all__ = [
    "ACTIVE_DATABASE_PATHS",
    "CONTENT_DATABASE_PATH",
    "DEFAULT_DATABASE_PATH",
    "LEGACY_RUNTIME_DATABASE_PATH",
    "MARKET_DATA_DATABASE_PATH",
    "TRADING_DATABASE_PATH",
    "clear_system_documents",
    "content_database_status",
    "database_status",
    "delete_runtime_state",
    "export_document_to_json",
    "import_json_document",
    "initialize_database",
    "initialize_content_database",
    "initialize_market_database",
    "list_documents",
    "list_market_series",
    "list_news_batches",
    "market_database_status",
    "market_series_parity",
    "mirror_daily_json_path_safely",
    "mirror_document_safely",
    "parity_for_document",
    "read_daily_json_dict",
    "read_daily_json_list",
    "read_document",
    "read_latest_document",
    "read_family_rows",
    "read_market_series",
    "read_market_series_safely",
    "read_news_batch",
    "read_runtime_state",
    "remove_family_documents_except",
    "replace_market_series",
    "replace_market_series_safely",
    "replace_news_batch",
    "replace_news_batch_safely",
    "sqlite_sidecar_paths",
    "write_runtime_state",
]
